from gensim.models import LdaMulticore

# load trained model
lda_model = LdaMulticore.load("data/models/lda_model.model")

print("\nTop words per topic:\n")

for i, topic in lda_model.print_topics(num_words=10): #view topic to see the top 10 words for each topic to understand the themes of the topics generated by LDA
    print(f"Topic {i}: {topic}")


    